Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> The test failed quite badly:
> 
> 14:25:14 Functional Test Case 2 :: Functional Test Case 2 - FTC150             | FAIL |
> 15:25:14 Resolving variable '${cli_cmd_output.rc}' failed: AttributeError: 'NoneType' object has no attribute 'rc'
> 
> Have you figured out why that happened? There was nothing like this in the Guilin branch?

The a1-controller never started successsfully.  Current CSIT on master fails as well since a couple of days due to the same reasons. I guesss we have to wait until the current CSIT works - when the sdnc-image is ok again.

Patch-set: 1